- routes.js
- src/Input.js
- src/screens/Components.js
- src/screens/Dashboard.js
- src/screens/Login.js
- src/screens/Register.js
Created the Login screen and styled it.
+++
Modifications to the Input component in the styling department.
> Login screen && Changes to the Input component

- src/Button.js
- src/screens/Article.js
- src/screens/ArticleCover.js
- src/screens/Login.js
- src/screens/Presentation.js
- src/screens/Register.js
Finished the Register screen using the Login screen as a base. 
Unwanted behavior:
- KeyboardAvoidingView is not working that great with our inputs
Things that are going to change with the next refactor regarding this screen:
- Button shadows
- View button for the password input ( the use should have the possibility to change that button however he pleases )
- The Input component's label seems too far away from the input itself
- NavBar component will allow full customization
> Register screen

- src/Button.js
The shadow is now customizable and removable
> Refactor: Button

- src/Button.js
- src/Input.js
Instead of the 'View' text we now have an eye Icon which is changed based on `this.state.password`
> Refactor: Input 

- src/AuthorSection.js
- src/Block.js
- src/Button.js
- src/Input.js
- src/NavBar.js
- src/screens/ArticleFeedv1.js
- src/screens/ArticleFeedv2.js
- src/screens/Components.js
- src/screens/Dashboard.js
- src/screens/Login.js
- src/screens/Presentation.js
- src/screens/Register.js
added propTypes and solved some ESLint issues
> Refactor  prop types

- src/NavBar.js
- src/screens/ArticleFeedv1.js
- src/screens/ArticleFeedv2.js
- src/screens/Components.js
- src/screens/Dashboard.js
- src/screens/Login.js
- src/screens/Presentation.js
- src/screens/Register.js
Changed the NavBar component and added the 'transparent' prop to every screen for an even more stylish look. 
Resolved a small problem with the iPhone image in the Presentation screen.
> iPhone X, XR, XS, XS Max compatibility

- src/AuthorSection.js
- src/Block.js
- src/Button.js
- src/Input.js
- src/NavBar.js
- src/theme.js
Not the best branch name but let's go with it.
The question is... should I create a new key inside the `theme.COLORS` object for every DEFAULT value I have in each component?
For example: 
Block had a default color and I created a key for it in the COLORS object.
> Theme.js injected in every component

- src/Block.js
- src/Button.js
Used `elevation: 1` for fixing the shadows on **Android**
> Shadow fix android

- src/Button.js
- src/Checkbox.js
- src/Slider.js
Bugfixes for our components. Checkbox has a new prop called `color` now which accepts our default colors or a string. Also had some fun with the Slider which is now a bit more customizable. Only changed some few things regarding the Button propTypes. 
Alin 🤙🏽
> Bugfixes 0.5

- package.json
- src/Card.js
- src/Icon.js
- src/Input.js
- src/NavBar.js
- src/helpers/getIconType.js
- src/index.js
Removed Expo from Galio and modified certain components
> V0.5.2 hotfix Expo SDK33

- src/Slider.js
Fixed typo in file src/Slider.js line 150 **style** -> **styles**
> Fixed typo in style issue #82

- package.json
- src/Card.js
- src/Radio.js
- src/Text.js
Fixed `style` props for `Card` and `Text` components.
> Hotfixes 0.6.2

- src/Input.js
> re-add onRef prop

- src/Link.js
- src/index.js
> feat: Link component

- src/Accordion.js
- src/atomic/atoms/Link.js
Paths fixed for Link and Accordion which caused the `dev` branch to fail rendering.
> path fixed

- src/Checkbox.js
PR to fix onChange callback getting called during the initial render. #133
> fix  onchange call during initial render

- src/theme/index.js
this is a PR to fix the withGalio() does not forward refs issue. #185
> forward ref to wrapped component  in withGalio HOC

- src/Switch.js
> switch trackColor hotfix

- src/Avatar.js
- src/Radio.js
fix to the onChange call during initial render in the radio component...
> Pr/radio fix - fix onchange call during initial render

- src/Card.js
- src/Checkbox.js
- src/NavBar.js
- src/Radio.js
- src/Toast.js
Fix imports issue occurring after 0.7.0 release
> fix Text, Icon imports bugs
